<a href="https://colab.research.google.com/github/luisosmx/Python-for-data-science-and-big-data-essential/blob/main/Introduccion_a_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/airline_dec_2008_50k.csv', nrows = 100000)

<ipython-input-2-2f9d7442c16a>:1: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/airline_dec_2008_50k.csv', nrows = 100000)

In [4]:
df.head(10)

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1,2008,12,1,1,NaN,1000,NaN,1100,WN,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
1,2,2008,12,1,1,NaN,1000,NaN,1110,US,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
2,3,2008,12,1,1,NaN,1000,NaN,1125,MQ,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,12,1,1,NaN,1000,NaN,1227,EV,...,NaN,NaN,1,C,0,NaN,NaN,NaN,NaN,NaN
4,5,2008,12,1,1,NaN,1000,NaN,1227,NW,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
5,6,2008,12,1,1,NaN,1005,NaN,1055,MQ,...,NaN,NaN,1,C,0,NaN,NaN,NaN,NaN,NaN
6,7,2008,12,1,1,NaN,1015,NaN,1145,MQ,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
7,8,2008,12,1,1,NaN,1020,NaN,1255,MQ,...,NaN,NaN,1,C,0,NaN,NaN,NaN,NaN,NaN
8,9,2008,12,1,1,NaN,1029,NaN,1112,YV,...,NaN,NaN,1,C,0,NaN,NaN,NaN,NaN,NaN
9,10,2008,12,1,1,NaN,1030,NaN,1201,US,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN

In [5]:
df.tail()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
49995,49996,2008,12,13,6,805.0,810,900.0,904,YV,...,10.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
49996,49997,2008,12,13,6,805.0,810,906.0,916,CO,...,7.0,13.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
49997,49998,2008,12,13,6,805.0,810,925.0,940,WN,...,2.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
49998,49999,2008,12,13,6,805.0,810,938.0,945,AA,...,4.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
49999,50000,2008,12,13,6,806.0,800,935.0,935,MQ,...,9.0,15.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [7]:
df = df.sample(frac = 1)

In [8]:
df.columns

Index(['Unnamed: 0', 'Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime',
       'CRSDepTime', 'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum',
       'TailNum', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [9]:
df.DepTime

32579    611.0
8123       NaN
15733      NaN
7100       NaN
31638    748.0
         ...
27094    854.0
39099    628.0
45604    735.0
15716      NaN
4537       NaN
Name: DepTime, Length: 50000, dtype: float64

In [10]:
df.dtypes

Unnamed: 0             int64
Year                   int64
Month                  int64
DayofMonth             int64
DayOfWeek              int64
DepTime              float64
CRSDepTime             int64
ArrTime              float64
CRSArrTime             int64
UniqueCarrier         object
FlightNum              int64
TailNum               object
ActualElapsedTime    float64
CRSElapsedTime         int64
AirTime              float64
ArrDelay             float64
DepDelay             float64
Origin                object
Dest                  object
Distance               int64
TaxiIn               float64
TaxiOut              float64
Cancelled              int64
CancellationCode      object
Diverted               int64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtype: object

In [11]:
df.values

array([[32580, 2008, 12, ..., nan, nan, nan],
       [8124, 2008, 12, ..., nan, nan, nan],
       [15734, 2008, 12, ..., nan, nan, nan],
       ...,
       [45605, 2008, 12, ..., 22.0, 0.0, 0.0],
       [15717, 2008, 12, ..., nan, nan, nan],
       [4538, 2008, 12, ..., nan, nan, nan]], dtype=object)

In [12]:
df2 = df.head(10)

In [14]:
df2.head(20)

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
32579,32580,2008,12,6,6,611.0,613,646.0,654,OO,...,9.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
8123,8124,2008,12,19,5,NaN,1656,NaN,1802,9E,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
15733,15734,2008,12,27,6,NaN,754,NaN,822,UA,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
7100,7101,2008,12,18,4,NaN,820,NaN,936,UA,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
31638,31639,2008,12,5,5,748.0,745,830.0,855,WN,...,3.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1047,1048,2008,12,5,5,NaN,1530,NaN,1630,WN,...,NaN,NaN,1,A,0,NaN,NaN,NaN,NaN,NaN
43347,43348,2008,12,11,4,557.0,600,648.0,646,EV,...,7.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5985,5986,2008,12,17,3,NaN,2034,NaN,2240,UA,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
8499,8500,2008,12,19,5,NaN,1935,NaN,2059,MQ,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN
10564,10565,2008,12,21,7,NaN,1510,NaN,1650,WN,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN