<a href="https://colab.research.google.com/github/luisosmx/Python-for-data-science-and-big-data-essential/blob/main/Transformaciones_de_la_base_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv('/content/airline_dec_2008_50k.csv')

<ipython-input-2-dcc53ca8087d>:2: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/airline_dec_2008_50k.csv')

In [3]:
df['HoursDelay'] = round(df['ArrDelay'] / 60)

In [4]:
df['HoursDelay'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: HoursDelay, dtype: float64

In [5]:
df.drop(['Diverted', 'Cancelled', 'Year'], axis = 1)

,Unnamed: 0,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,Distance,TaxiIn,TaxiOut,CancellationCode,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,HoursDelay
0,1,12,1,1,NaN,1000,NaN,1100,WN,16,...,239,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
1,2,12,1,1,NaN,1000,NaN,1110,US,2122,...,185,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN
2,3,12,1,1,NaN,1000,NaN,1125,MQ,3155,...,417,NaN,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN
3,4,12,1,1,NaN,1000,NaN,1227,EV,4980,...,403,NaN,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN
4,5,12,1,1,NaN,1000,NaN,1227,NW,1406,...,235,NaN,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,12,13,6,805.0,810,900.0,904,YV,2891,...,110,10.0,16.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.0
49996,49997,12,13,6,805.0,810,906.0,916,CO,414,...,224,7.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.0
49997,49998,12,13,6,805.0,810,925.0,940,WN,505,...,423,2.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.0
49998,49999,12,13,6,805.0,810,938.0,945,AA,1336,...,551,4.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,-0.0
49999,50000,12,13,6,806.0,800,935.0,935,MQ,4673,...,426,9.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0